repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.3
    hooks:
      # Run the linter.
      - id: ruff-check
        files: ^backend/
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        files: ^backend/
        types_or: [python, pyi]
        args: [./backend]
  - repo: https://github.com/crate-ci/typos
    rev: v1.34.0
    hooks:
      - id: typos
